apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 5000
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
     metadata:
       labels:
         app: payment-service
     spec:
       containers:
         - name: payment-service
           image: pank05081985/scalable-payment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service
spec:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service

  
    
