name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: List file in current directory
          run: ls
          working-directory: ./payment
      
        - name: Build and Push Docker Image
          run:  docker build -t pank05081985/scalable-payment:v1 .

        - name: Publish the image to Docker hub
          run: docker push pank05081985/scalable-payment:latest
